#ifndef haltypes_hpp
#define haltypes_hpp

#include <ntifs.h>
#include <ntddk.h>
#include <cstdint>

typedef struct _HAL_PRIVATE_DISPATCH {
	unsigned int Version;
	_BUS_HANDLER* (__fastcall* HalHandlerForBus)(_INTERFACE_TYPE, unsigned int);
	_BUS_HANDLER* (__fastcall* HalHandlerForConfigSpace)(_BUS_DATA_TYPE, unsigned int);
	void(__fastcall* HalLocateHiberRanges)(void*);
	int(__fastcall* HalRegisterBusHandler)(_INTERFACE_TYPE, _BUS_DATA_TYPE, unsigned int, _INTERFACE_TYPE, unsigned int, unsigned int, int(__fastcall*)(_BUS_HANDLER*), _BUS_HANDLER**);
	void(__fastcall* HalSetWakeEnable)(unsigned __int8);
	int(__fastcall* HalSetWakeAlarm)(unsigned __int64, unsigned __int64);
	unsigned __int8(__fastcall* HalPciTranslateBusAddress)(_INTERFACE_TYPE, unsigned int, _LARGE_INTEGER, unsigned int*, _LARGE_INTEGER*);
	int(__fastcall* HalPciAssignSlotResources)(_UNICODE_STRING*, _UNICODE_STRING*, _DRIVER_OBJECT*, _DEVICE_OBJECT*, _INTERFACE_TYPE, unsigned int, unsigned int, _CM_RESOURCE_LIST**);
	void(__fastcall* HalHaltSystem)();
	unsigned __int8(__fastcall* HalFindBusAddressTranslation)(_LARGE_INTEGER, unsigned int*, _LARGE_INTEGER*, unsigned __int64*, unsigned __int8);
	unsigned __int8(__fastcall* HalResetDisplay)();
	int(__fastcall* HalAllocateMapRegisters)(void*, unsigned int, unsigned int, _MAP_REGISTER_ENTRY*);
	int(__fastcall* KdSetupPciDeviceForDebugging)(void*, _DEBUG_DEVICE_DESCRIPTOR*);
	int(__fastcall* KdReleasePciDeviceForDebugging)(_DEBUG_DEVICE_DESCRIPTOR*);
	void* (__fastcall* KdGetAcpiTablePhase0)(_LOADER_PARAMETER_BLOCK*, unsigned int);
	void(__fastcall* KdCheckPowerButton)();
	unsigned __int8(__fastcall* HalVectorToIDTEntry)(unsigned int);
	void* (__fastcall* KdMapPhysicalMemory64)(_LARGE_INTEGER, unsigned int, unsigned __int8);
	void(__fastcall* KdUnmapVirtualAddress)(void*, unsigned int, unsigned __int8);
	unsigned int(__fastcall* KdGetPciDataByOffset)(unsigned int, unsigned int, void*, unsigned int, unsigned int);
	unsigned int(__fastcall* KdSetPciDataByOffset)(unsigned int, unsigned int, void*, unsigned int, unsigned int);
	unsigned int(__fastcall* HalGetInterruptVectorOverride)(_INTERFACE_TYPE, unsigned int, unsigned int, unsigned int, unsigned __int8*, unsigned __int64*);
	int(__fastcall* HalGetVectorInputOverride)(unsigned int, _GROUP_AFFINITY*, unsigned int*, _KINTERRUPT_POLARITY*, void*);
	int(__fastcall* HalLoadMicrocode)(void*);
	int(__fastcall* HalUnloadMicrocode)();
	int(__fastcall* HalPostMicrocodeUpdate)();
	int(__fastcall* HalAllocateMessageTargetOverride)(_DEVICE_OBJECT*, _GROUP_AFFINITY*, unsigned int, _KINTERRUPT_MODE, unsigned __int8, unsigned int*, unsigned __int8*, unsigned int*);
	void(__fastcall* HalFreeMessageTargetOverride)(_DEVICE_OBJECT*, unsigned int, _GROUP_AFFINITY*);
	int(__fastcall* HalDpReplaceBegin)(void*, void**);
	void(__fastcall* HalDpReplaceTarget)(void*);
	int(__fastcall* HalDpReplaceControl)(unsigned int, void*);
	void(__fastcall* HalDpReplaceEnd)(void*);
	void(__fastcall* HalPrepareForBugcheck)(unsigned int);
	unsigned __int8(__fastcall* HalQueryWakeTime)(unsigned __int64*, unsigned __int64*);
	void(__fastcall* HalReportIdleStateUsage)(unsigned __int8, _KAFFINITY_EX*);
	void(__fastcall* HalTscSynchronization)(unsigned __int8, unsigned int*);
	int(__fastcall* HalWheaInitProcessorGenericSection)(_WHEA_ERROR_RECORD_SECTION_DESCRIPTOR*, _WHEA_PROCESSOR_GENERIC_ERROR_SECTION*);
	void(__fastcall* HalStopLegacyUsbInterrupts)(_SYSTEM_POWER_STATE);
	int(__fastcall* HalReadWheaPhysicalMemory)(_LARGE_INTEGER, unsigned int, void*);
	int(__fastcall* HalWriteWheaPhysicalMemory)(_LARGE_INTEGER, unsigned int, void*);
	int(__fastcall* HalDpMaskLevelTriggeredInterrupts)();
	int(__fastcall* HalDpUnmaskLevelTriggeredInterrupts)();
	int(__fastcall* HalDpGetInterruptReplayState)(void*, void**);
	int(__fastcall* HalDpReplayInterrupts)(void*);
	unsigned __int8(__fastcall* HalQueryIoPortAccessSupported)();
	int(__fastcall* KdSetupIntegratedDeviceForDebugging)(void*, _DEBUG_DEVICE_DESCRIPTOR*);
	int(__fastcall* KdReleaseIntegratedDeviceForDebugging)(_DEBUG_DEVICE_DESCRIPTOR*);
	void(__fastcall* HalGetEnlightenmentInformation)(void*);
	void* (__fastcall* HalAllocateEarlyPages)(_LOADER_PARAMETER_BLOCK*, unsigned int, unsigned __int64*, unsigned int);
	void* (__fastcall* HalMapEarlyPages)(unsigned __int64, unsigned int, unsigned int);
	void* Dummy1;
	void* Dummy2;
	void(__fastcall* HalNotifyProcessorFreeze)(unsigned __int8, unsigned __int8);
	int(__fastcall* HalPrepareProcessorForIdle)(unsigned int);
	void(__fastcall* HalRegisterLogRoutine)(void*);
	void(__fastcall* HalResumeProcessorFromIdle)();
	void* Dummy;
	unsigned int(__fastcall* HalVectorToIDTEntryEx)(unsigned int);
	int(__fastcall* HalSecondaryInterruptQueryPrimaryInformation)(void*, unsigned int*);
	int(__fastcall* HalMaskInterrupt)(unsigned int, unsigned int);
	int(__fastcall* HalUnmaskInterrupt)(unsigned int, unsigned int);
	unsigned __int8(__fastcall* HalIsInterruptTypeSecondary)(unsigned int, unsigned int);
	int(__fastcall* HalAllocateGsivForSecondaryInterrupt)(char*, unsigned __int16, unsigned int*);
	int(__fastcall* HalAddInterruptRemapping)(unsigned int, unsigned int, void*, unsigned __int8, void*, unsigned int);
	void(__fastcall* HalRemoveInterruptRemapping)(unsigned int, unsigned int, void*, unsigned __int8, void*, unsigned int);
	void(__fastcall* HalSaveAndDisableHvEnlightenment)();
	void(__fastcall* HalRestoreHvEnlightenment)();
	void(__fastcall* HalFlushIoBuffersExternalCache)(_MDL*, unsigned __int8);
	void(__fastcall* HalFlushExternalCache)(unsigned __int8);
	int(__fastcall* HalPciEarlyRestore)(_SYSTEM_POWER_STATE);
	int(__fastcall* HalGetProcessorId)(unsigned int, unsigned int*, unsigned int*);
	int(__fastcall* HalAllocatePmcCounterSet)(unsigned int, _KPROFILE_SOURCE*, unsigned int, struct _HAL_PMC_COUNTERS**);
	void(__fastcall* HalCollectPmcCounters)(struct _HAL_PMC_COUNTERS*, unsigned __int64*);
	void(__fastcall* HalFreePmcCounterSet)(struct _HAL_PMC_COUNTERS*);
	int(__fastcall* HalProcessorHalt)(unsigned int, void*, int(__fastcall*)(void*));
	unsigned __int64(__fastcall* HalTimerQueryCycleCounter)(unsigned __int64*);
	void* Dummy3;
	void(__fastcall* HalPciMarkHiberPhase)();
	int(__fastcall* HalQueryProcessorRestartEntryPoint)(_LARGE_INTEGER*);
	int(__fastcall* HalRequestInterrupt)(unsigned int);
	int(__fastcall* HalEnumerateUnmaskedInterrupts)(unsigned __int8(__fastcall*)(void*, void*), void*, void*);
	void(__fastcall* HalFlushAndInvalidatePageExternalCache)(_LARGE_INTEGER);
	int(__fastcall* KdEnumerateDebuggingDevices)(void*, _DEBUG_DEVICE_DESCRIPTOR*, KD_CALLBACK_ACTION(__fastcall*)(_DEBUG_DEVICE_DESCRIPTOR*));
	void(__fastcall* HalFlushIoRectangleExternalCache)(_MDL*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned __int8);
	void(__fastcall* HalPowerEarlyRestore)(unsigned int);
	int(__fastcall* HalQueryCapsuleCapabilities)(void*, unsigned int, unsigned __int64*, unsigned int*);
	int(__fastcall* HalUpdateCapsule)(void*, unsigned int, _LARGE_INTEGER);
	unsigned __int8(__fastcall* HalPciMultiStageResumeCapable)();
	void(__fastcall* HalDmaFreeCrashDumpRegisters)(unsigned int);
	unsigned __int8(__fastcall* HalAcpiAoacCapable)();
	int(__fastcall* HalInterruptSetDestination)(void*, _GROUP_AFFINITY*, unsigned int*);
	void(__fastcall* HalGetClockConfiguration)(void*);
	void(__fastcall* HalClockTimerActivate)(unsigned __int8);
	void(__fastcall* HalClockTimerInitialize)();
	void(__fastcall* HalClockTimerStop)();
	int(__fastcall* HalClockTimerArm)(void*, unsigned __int64, unsigned __int64*);
	unsigned __int8(__fastcall* HalTimerOnlyClockInterruptPending)();
	void* (__fastcall* HalAcpiGetMultiNode)();
	void(__fastcall* (__fastcall* HalPowerSetRebootHandler)(void(__fastcall*)(unsigned int, volatile int*)))(unsigned int, volatile int*);
	void(__fastcall* HalIommuRegisterDispatchTable)(void*);
	void(__fastcall* HalTimerWatchdogStart)();
	void(__fastcall* HalTimerWatchdogResetCountdown)();
	void(__fastcall* HalTimerWatchdogStop)();
	unsigned __int8(__fastcall* HalTimerWatchdogGeneratedLastReset)();
	int(__fastcall* HalTimerWatchdogTriggerSystemReset)(unsigned __int8);
	int(__fastcall* HalInterruptVectorDataToGsiv)(void*, unsigned int*);
	int(__fastcall* HalInterruptGetHighestPriorityInterrupt)(unsigned int*, unsigned __int8*);
	int(__fastcall* HalProcessorOn)(unsigned int);
	int(__fastcall* HalProcessorOff)();
	int(__fastcall* HalProcessorFreeze)();
	int(__fastcall* HalDmaLinkDeviceObjectByToken)(unsigned __int64, _DEVICE_OBJECT*);
	int(__fastcall* HalDmaCheckAdapterToken)(unsigned __int64);
	void* Dummy4;
	int(__fastcall* HalTimerConvertPerformanceCounterToAuxiliaryCounter)(unsigned __int64, unsigned __int64*, unsigned __int64*);
	int(__fastcall* HalTimerConvertAuxiliaryCounterToPerformanceCounter)(unsigned __int64, unsigned __int64*, unsigned __int64*);
	int(__fastcall* HalTimerQueryAuxiliaryCounterFrequency)(unsigned __int64*);
	int(__fastcall* HalConnectThermalInterrupt)(unsigned __int8(__fastcall*)(_KINTERRUPT*, void*));
	unsigned __int8(__fastcall* HalIsEFIRuntimeActive)();
	unsigned __int8(__fastcall* HalTimerQueryAndResetRtcErrors)(unsigned __int8);
	void(__fastcall* HalAcpiLateRestore)();
	int(__fastcall* KdWatchdogDelayExpiration)(unsigned __int64*);
	int(__fastcall* HalGetProcessorStats)(uint32_t, unsigned int, unsigned int, unsigned __int64*);
	unsigned __int64(__fastcall* HalTimerWatchdogQueryDueTime)(unsigned __int8);
	int(__fastcall* HalConnectSyntheticInterrupt)(unsigned __int8(__fastcall*)(_KINTERRUPT*, void*));
	void(__fastcall* HalPreprocessNmi)(unsigned int);
	int(__fastcall* HalEnumerateEnvironmentVariablesWithFilter)(unsigned int, unsigned __int8(__fastcall*)(const _GUID*, const wchar_t*), void*, unsigned int*);
	int(__fastcall* HalCaptureLastBranchRecordStack)(unsigned int, void*, unsigned int*);
	unsigned __int8(__fastcall* HalClearLastBranchRecordStack)();
	int(__fastcall* HalConfigureLastBranchRecord)(unsigned int, unsigned int);
	unsigned __int8(__fastcall* HalGetLastBranchInformation)(unsigned int*, unsigned int*);
	void(__fastcall* HalResumeLastBranchRecord)(unsigned __int8);
	int(__fastcall* HalStartLastBranchRecord)(unsigned int, unsigned int*);
	int(__fastcall* HalStopLastBranchRecord)(unsigned int);
	int(__fastcall* HalIommuBlockDevice)(void*);
	int(__fastcall* HalIommuUnblockDevice)(void*, void**);
	int(__fastcall* HalGetIommuInterface)(unsigned int, _DMA_IOMMU_INTERFACE*);
	int(__fastcall* HalRequestGenericErrorRecovery)(void*, unsigned int*);
	int(__fastcall* HalTimerQueryHostPerformanceCounter)(unsigned __int64*);
	int(__fastcall* HalTopologyQueryProcessorRelationships)(unsigned int, unsigned int, unsigned __int8*, unsigned __int8*, unsigned __int8*, unsigned int*, unsigned int*);
	void(__fastcall* HalInitPlatformDebugTriggers)();
	void(__fastcall* HalRunPlatformDebugTriggers)(unsigned __int8);
	void* (__fastcall* HalTimerGetReferencePage)();
	int(__fastcall* HalGetHiddenProcessorPowerInterface)(void*);
	unsigned int(__fastcall* HalGetHiddenProcessorPackageId)(unsigned int);
	unsigned int(__fastcall* HalGetHiddenPackageProcessorCount)(unsigned int);
	int(__fastcall* HalGetHiddenProcessorApicIdByIndex)(unsigned int, unsigned int*);
	int(__fastcall* HalRegisterHiddenProcessorIdleState)(unsigned int, unsigned __int64);
	void(__fastcall* HalIommuReportIommuFault)(unsigned __int64, _FAULT_INFORMATION*);
	unsigned __int8(__fastcall* HalIommuDmaRemappingCapable)(void*, unsigned int*);
}HAL_PRIVATE_DISPATCH, * PHAL_PRIVATE_DISPATCH;

#endif // !haltypes_hpp